#ifndef APP_HM0360_MIPI_CFG_H_
#define APP_HM0360_MIPI_CFG_H_

#define CIS_MIRROR_SETTING				(0x00) //0x00: off/0x01:H-Mirror/0x02:V-Mirror/0x03:HV-Mirror
#define CIS_I2C_ID						(0x24)

#define CISDP_INIT_TYPE                 (APP_INIT_TYPE_VIDEO_STREAM)
#define CISDP_SENSORCTRL_MCLK_DIV       (SENSORCTRL_MCLK_DIV3)
#define CISDP_CIS_XHSUTDOWN_PIN         (AON_GPIO2)

/*
 * HM11B1/HM2170 1-bit parser setting
 */
#define SCLK_72M_UTG 			5 	//8*24/72 if < 5, set 5
#define SCLK_36M_UTG 			6 	//8*24/36
#define SCLK_9M_UTG 			(20) //ceil(8*24/9.375 = 20.48) = 20
#define SCLK_UTG				(SCLK_9M_UTG)
/*
* HM2170 1-bit parser setting: PACK MODE
* REG_INP_RX_LBUF_INSERT_H_FPORCH = freq(inp_cclk) * sensor_hblank_time / 2
*/
#define SCLK_9M_FPORCH					(2047)
#define SCLK_72M_FPORCH					(542)
#define RX_LBUF_INSERT_H_FPORCH			(SCLK_72M_FPORCH)

#define SENCTRL_STREAM_TYPE_AOS  	SENSORDPLIB_STREAM_NONEAOS //dummy
#define SENCTRL_STREAM_TYPE_NONAOS	SENSORDPLIB_STREAM_NONEAOS //dummy

/*
 * SENDPLIB PARAMETERS
 */
#define SENDPLIB_MIPIRX_LANE_NB 			1

/*
 * DP SENCTRL CFG
 */
#define SENCTRL_SENSOR_TYPE			SENSORDPLIB_SENSOR_HM2170_MIPI

#if (CIS_ENABLE_HX_AUTOI2C == 0x00)
#define SENCTRL_STREAM_TYPE			SENSORDPLIB_STREAM_NONEAOS
#elif (CIS_ENABLE_HX_AUTOI2C == 0x01)
#define SENCTRL_STREAM_TYPE			SENSORDPLIB_STREAM_NONEAOS_AUTOI2C
#elif (CIS_ENABLE_HX_AUTOI2C == 0x02)
#define SENCTRL_STREAM_TYPE			SENSORDPLIB_STREAM_NONEAOS_AUTOI2C_XSLEEP_HIGH
#endif

#define SENCTRL_SENSOR_WIDTH 		640
#define SENCTRL_SENSOR_HEIGHT 		480


#endif